export const flightsByDays = {
    Sun: [
        'UA618',
        'AC8840',
        'UA2285',
        'AC566',
        'UA5687',
        'UA2423',
        'AA6072',
        'AC200',
        'AS2269',
        'AC8089',
        'AC550',
        'AC8839',
        'UA784',
        'UA5791',
        'UA1968',
        'AC569',
        'UA460',
        'DL2494',
        'UA780',
        'DL1687',
        'AS367',
        'AS1922',
    ],
    Mon: [
        'UA618',
        'AC8840',
        'UA2285',
        'AC566',
        'UA5687',
        'AS2166',
        'AA6072',
        'AC200',
        'AS2269',
        'AC8089',
        'AC550',
        'UA784',
        'UA5791',
        'UA1968',
        'AC569',
        'UA460',
        'DL2494',
        'WN831',
        'UA780',
        'DL1687',
        'AS367',
        'AS1922',
    ],
    Tue: [
        'UA618',
        'AC8840',
        'UA2285',
        'AC566',
        'UA5687',
        'AS2166',
        'AA6072',
        'AC200',
        'AS2269',
        'AC8089',
        'AC550',
        'AC8839',
        'UA784',
        'UA5791',
        'UA1968',
        'AC569',
        'UA460',
        'DL2494',
        'WN831',
        'UA780',
        'DL1687',
        'AS367',
        'AS1922',
    ],
    Wed: [
        'UA618',
        'AC8840',
        'UA2285',
        'AC566',
        'UA5687',
        'UA2423',
        'AS2166',
        'AA6072',
        'AC200',
        'AS2269',
        'AC8089',
        'AC550',
        'AC8839',
        'UA784',
        'UA5791',
        'UA1968',
        'AC569',
        'UA460',
        'DL2494',
        'WN831',
        'UA780',
        'DL1687',
        'AS367',
        'AS1922',
    ],
    Thu: [
        'UA618',
        'AC8840',
        'UA2285',
        'AC566',
        'UA5687',
        'UA2423',
        'AS2166',
        'AA6072',
        'AC200',
        'AS2269',
        'AC8089',
        'AC550',
        'AC8839',
        'UA784',
        'UA5791',
        'UA1968',
        'AC569',
        'UA460',
        'DL2494',
        'WN831',
        'UA780',
        'DL1687',
        'AS367',
        'AS1922',
    ],
    Fri: [
        'UA618',
        'AC8840',
        'UA2285',
        'AC566',
        'UA5687',
        'UA2423',
        'AS2166',
        'AA6072',
        'AC200',
        'AS2269',
        'AC8089',
        'AC550',
        'AC8839',
        'UA784',
        'UA5791',
        'UA1968',
        'AC569',
        'UA460',
        'DL2494',
        'WN831',
        'UA780',
        'DL1687',
        'AS367',
        'AS1922',
    ],
    Sat: [
        'UA618',
        'AC8840',
        'UA2285',
        'AC566',
        'UA5687',
        'AS2166',
        'AA6072',
        'AC200',
        'AS2269',
        'AC8089',
        'AC550',
        'AC8839',
        'UA784',
        'UA5791',
        'UA1968',
        'AC569',
        'UA460',
        'DL2494',
        'UA780',
        'DL1687',
        'AS367',
        'AS1922',
    ],
}

export const flights_schedules = {
    YVR: {
        SFO: {
            0: [{
                    depart: '06:00',
                    arrive: '08:25',
                    airline: 'United Airline',
                    airlineCode: 'UA618',
                    totalTime: '2h 25m',
                },
                {
                    depart: '08:40',
                    arrive: '11:13',
                    airline: 'Air Canada',
                    airlineCode: 'AC8840',
                    totalTime: '2h 33m',
                },
                {
                    depart: '11:43',
                    arrive: '14:08',
                    airline: 'United Airline',
                    airlineCode: 'UA2285',
                    totalTime: '2h 25m',
                },
                {
                    depart: '13:40',
                    arrive: '16:04',
                    airline: 'Air Canada',
                    airlineCode: 'AC566',
                    totalTime: '2h 24m',
                },
                {
                    depart: '13:56',
                    arrive: '16:25',
                    airline: 'United Airlines',
                    airlineCode: 'UA5687',
                    totalTime: '2h 29m',
                },
                {
                    depart: '19:16',
                    arrive: '21:43',
                    airline: 'United Airlines',
                    airlineCode: 'UA2423',
                    totalTime: '2h 27m',
                },
            ],
            1: [{
                    depart: '06:00',
                    arrive: '10:10',
                    airline: 'Alaska Airlines',
                    airlineCode: 'AS2166',
                    totalTime: '4h 10m',
                    viaAirlineCode: 'SEA',
                },
                {
                    depart: '06:44',
                    arrive: '13:15',
                    airline: 'American Airlines',
                    airlineCode: 'AA6072',
                    totalTime: '6h 31m',
                    viaAirlineCode: 'LAX',
                },
                {
                    depart: '07:30',
                    arrive: '15:21',
                    airline: 'Air Cananda',
                    airlineCode: 'AC200',
                    totalTime: '7h 51m',
                    viaAirlineCode: 'YYC',
                },
                {
                    depart: '08:00',
                    arrive: '12:00',
                    airline: 'Alaska Cananda',
                    airlineCode: 'AS2269',
                    totalTime: '4h 0m',
                    viaAirlineCode: 'SEA',
                },
                {
                    depart: '08:10',
                    arrive: '12:08',
                    airline: 'Air Cananda',
                    airlineCode: 'AC8089',
                    totalTime: '3h 58m',
                    viaAirlineCode: 'SEA',
                },
                {
                    depart: '08:40',
                    arrive: '14:38',
                    airline: 'Air Cananda',
                    airlineCode: 'AC550',
                    totalTime: '5h 58m',
                    viaAirlineCode: 'LAX',
                },
            ],
        },
    },
    SFO: {
        YVR: {
            0: [{
                    depart: '08:20',
                    arrive: '10:42',
                    airline: 'Air Canada',
                    airlineCode: 'AC8839',
                    totalTime: '2h 22m',
                },
                {
                    depart: '08:30',
                    arrive: '10:55',
                    airline: 'United Airlines',
                    airlineCode: 'UA784',
                    totalTime: '2h 25m',
                },
                {
                    depart: '10:40',
                    arrive: '13:09',
                    airline: 'United Airlines',
                    airlineCode: 'UA5791',
                    totalTime: '2h 29m',
                },
                {
                    depart: '16:04',
                    arrive: '18:21',
                    airline: 'United Airlines',
                    airlineCode: 'UA1968',
                    totalTime: '2h 17m',
                },
                {
                    depart: '16:55',
                    arrive: '19:13',
                    airline: 'Air Canada',
                    airlineCode: 'AC569',
                    totalTime: '2h 18m',
                },
                {
                    depart: '19:20',
                    arrive: '21:38',
                    airline: 'United Airlines',
                    airlineCode: 'UA460',
                    totalTime: '2h 18m',
                },
            ],
            1: [{
                    depart: '06:00',
                    arrive: '12:21',
                    airline: 'Delta Airlines',
                    airlineCode: 'DL2494',
                    totalTime: '6h 21m',
                    viaAirlineCode: 'SLC',
                },
                {
                    depart: '06:00',
                    arrive: '14:25',
                    airline: 'Southwest Airlines',
                    airlineCode: 'WN831',
                    totalTime: '8h 25m',
                    viaAirlineCode: 'LAX',
                },
                {
                    depart: '06:25',
                    arrive: '10:31',
                    airline: 'United Airlines',
                    airlineCode: 'UA780',
                    totalTime: '4h 06m',
                    viaAirlineCode: 'SEA',
                },
                {
                    depart: '06:35',
                    arrive: '10:36',
                    airline: 'Delta Airlines',
                    airlineCode: 'DL1687',
                    totalTime: '4h 01m',
                    viaAirlineCode: 'SEA',
                },
                {
                    depart: '07:00',
                    arrive: '11:48',
                    airline: 'Alaska Airlines',
                    airlineCode: 'AS367',
                    totalTime: '4h 48m',
                    viaAirlineCode: 'PDX',
                },
                {
                    depart: '07:00',
                    arrive: '13:27',
                    airline: 'Alaska Airlines',
                    airlineCode: 'AS1922',
                    totalTime: '6h 27m',
                    viaAirlineCode: 'LAX',
                },
            ],
        },
    },
}

export const prices = {
    Economy: { low: 190, high: 450 },
    'Premium Economy': { low: 558, high: 650 },
    Business: { low: 690, high: 1483 },
    'First Class': { low: 1917, high: 2409 },
}